fixtures:
  repositories:
    "stdlib": "https://github.com/puppetlabs/puppetlabs-stdlib"
    "justin8-systemd": "https://github.com/justin8/justin8-systemd"
  symlinks:
    "splunk": "#{source_dir}"

